repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort

    - repo: https://github.com/pycqa/pylint
      rev: v3.3.2
      hooks:
          - id: pylint

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.14.0"
      hooks:
          - id: mypy

    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
